In [1]:
import pandas as pd
import numpy as np
import pickle

import sys
sys.path.insert(0, '..')

# Load your model to check the 'expected_features'
with open('../model.pkl', 'rb') as f:
    model = pickle.load(f)

In [2]:
model

{'weights': array([ 0.10420549, -0.52079175, -0.41705808,  0.12061994,  0.24286792,
         0.44700312,  0.03788581, -0.06492184,  0.19082469,  0.53794669,
         0.32588546,  0.07008246,  0.15135067,  0.22252467, -0.06476562,
         0.37409437,  0.06320299,  0.01156817,  0.0409008 ,  0.05777237,
         0.11835459, -0.30667039, -0.11492176,  0.12208219, -0.1908274 ,
        -0.78291617, -0.12055786]),
 'bias': np.float64(-1.4475714946980056),
 'mu': volume                  9.201526e+06
 pct_change_1d           3.303557e-04
 rsi                     4.938905e+01
 adx                     3.095551e+01
 volume^2                1.139406e+14
 pct_change_1d^2         3.340574e-04
 rsi^2                   2.610649e+03
 adx^2                   1.103528e+03
 volatility^2            4.175331e+00
 volume*pct_change_1d    1.500027e+04
 volume*rsi              4.684029e+08
 volume*adx              2.940709e+08
 volume*corr             3.600314e+06
 volume*volatility       1.814237e+07
 pct_change_1d*rsi       1.030347e-01
 pct_change_1d*adx       1.422425e-02
 pct_change_1d*corr      5.723908e-05
 rsi*adx                 1.520124e+03
 rsi*corr                1.786711e+01
 rsi*volatility          9.298190e+01
 adx*corr                1.238225e+01
 adx*volatility          6.125020e+01
 corr*volatility         7.242037e-01
 dtype: float64,
 'sigma': volume                  5.415230e+06
 pct_change_1d           1.829053e-02
 rsi                     1.310252e+01
 adx                     1.206415e+01
 volume^2                1.537159e+14
 pct_change_1d^2         6.073698e-04
 rsi^2                   1.386189e+03
 adx^2                   8.417080e+02
 volatility^2            3.857020e+00
 volume*pct_change_1d    2.501494e+05
 volume*rsi              3.466572e+08
 volume*adx              2.309509e+08
 volume*corr             5.423887e+06
 volume*volatility       1.520310e+07
 pct_change_1d*rsi       9.402993e-01
 pct_change_1d*adx       6.158278e-01
 pct_change_1d*corr      1.072959e-02
 rsi*adx                 7.884670e+02
 rsi*corr                2.433179e+01
 rsi*volatility          4.343421e+01
 adx*corr                1.628663e+01
 adx*volatility          4.308625e+01
 corr*volatility         9.665887e-01
 dtype: float64,
 'features_to_scale': ['volume',
  'pct_change_1d',
  'rsi',
  'adx',
  'volume^2',
  'pct_change_1d^2',
  'rsi^2',
  'adx^2',
  'volatility^2',
  'volume*pct_change_1d',
  'volume*rsi',
  'volume*adx',
  'volume*corr',
  'volume*volatility',
  'pct_change_1d*rsi',
  'pct_change_1d*adx',
  'pct_change_1d*corr',
  'rsi*adx',
  'rsi*corr',
  'rsi*volatility',
  'adx*corr',
  'adx*volatility',
  'corr*volatility']}

In [3]:
from utilities_notebook import zscore_normalize_features, apply_zscore_normalization, get_engineered_data
import yfinance as yf

data = yf.download('5296.KL', period='30d', multi_level_index=False)
data

[*********************100%***********************]  1 of 1 completed

            Close  High   Low  Open    Volume
Date
2026-01-06   1.52  1.53  1.51  1.53  15785800
2026-01-07   1.56  1.56  1.50  1.52  12231500
2026-01-08   1.54  1.55  1.53  1.55   9367900
2026-01-09   1.58  1.59  1.53  1.55  17083700
2026-01-12   1.63  1.63  1.56  1.58  21047500
2026-01-13   1.67  1.69  1.62  1.63  20931300
2026-01-14   1.73  1.73  1.65  1.67  22948000
2026-01-15   1.72  1.74  1.68  1.73  20878000
2026-01-16   1.73  1.73  1.70  1.72  21296100
2026-01-19   1.73  1.73  1.73  1.73         0
2026-01-20   1.74  1.77  1.69  1.71  20655500
2026-01-21   1.78  1.79  1.74  1.74  19521400
2026-01-22   1.80  1.81  1.75  1.78  27050900
2026-01-23   1.81  1.87  1.79  1.80  34530300
2026-01-26   1.88  1.90  1.81  1.81  31199100
2026-01-27   1.90  1.91  1.88  1.88  18945500
2026-01-28   1.87  1.90  1.86  1.90  12225800
2026-01-29   1.83  1.87  1.81  1.87  12947400
2026-01-30   1.83  1.86  1.82  1.83  12121200
2026-02-03   1.79  1.87  1.79  1.84  18049500
2026-02-04   1.81  1.83  1.79  1.79  10886200
2026-02-05   1.77  1.83  1.76  1.81  15539000
2026-02-06   1.79  1.82  1.75  1.75  11225400
2026-02-09   1.83  1.85  1.80  1.80   8220500
2026-02-10   1.82  1.85  1.81  1.84  12361400
2026-02-11   1.86  1.87  1.82  1.83   8777000
2026-02-12   1.84  1.86  1.81  1.85  11216600
2026-02-13   1.85  1.86  1.82  1.84  10172400
2026-02-16   1.84  1.88  1.83  1.85   6330000
2026-02-19   1.87  1.89  1.84  1.84   6376600

In [4]:
future_1d_returns, data_fe = get_engineered_data(data)
data_fe

,volume,pct_change_1d,rsi,adx,corr,volatility,volume^2,volume*pct_change_1d,volume*rsi,volume*adx,...,rsi^2,rsi*adx,rsi*corr,rsi*volatility,adx^2,adx*corr,adx*volatility,corr^2,corr*volatility,volatility^2
Date,,,,,,,,,,,,,,,,,,,,,
2026-02-03,18049500,-0.021858,63.397336,80.344530,0.579944,1.939089,325784450250000,-394525.380439,1.144290e+09,1.450179e+09,...,4019.222264,5093.629203,36.766900,122.933099,6455.243514,46.595322,155.795221,0.336335,1.124563,3.760067
2026-02-04,10886200,0.011173,66.008334,75.103769,0.258942,1.953325,118509350440000,121633.406146,7.185799e+08,8.175947e+08,...,4357.100155,4957.474676,17.092322,128.935708,5640.576139,19.447511,146.702046,0.067051,0.505798,3.815477
2026-02-05,15539000,-0.022099,56.976481,68.652448,-0.180845,1.989508,241460521000000,-343402.998278,8.853575e+08,1.066790e+09,...,3246.319334,3911.574849,-10.303931,113.355139,4713.158572,-12.415475,136.584564,0.032705,-0.359793,3.958140
2026-02-06,11225400,0.011299,60.015915,62.317463,-0.512682,1.989921,126009605160000,126840.558368,6.737027e+08,6.995384e+08,...,3601.910040,3740.039534,-30.769054,119.426903,3883.466149,-31.949015,124.006800,0.262842,-1.020196,3.959784
2026-02-09,8220500,0.022346,65.441326,57.917820,-0.847745,2.112623,67576620250000,183698.700212,5.379604e+08,4.761134e+08,...,4282.567195,3790.218952,-55.477556,138.252884,3354.473858,-49.099541,122.358547,0.718672,-1.790966,4.463178
2026-02-10,12361400,-0.005464,63.064346,53.958141,-0.878577,1.656947,152804209960000,-67548.567876,7.795636e+08,6.669982e+08,...,3977.111719,3402.834890,-55.406864,104.494259,2911.481021,-47.406365,89.405764,0.771897,-1.455755,2.745472
2026-02-11,8777000,0.021978,68.198192,51.224668,-0.680924,1.794609,77035729000000,192900.909377,5.985755e+08,4.495989e+08,...,4650.993350,3493.429709,-46.437758,122.389086,2623.966585,-34.880085,91.928248,0.463657,-1.221992,3.220621
2026-02-12,11216600,-0.010753,63.309492,48.087709,-0.511632,1.758246,125812115560000,-120608.486202,7.101172e+08,5.393806e+08,...,4008.091789,3044.408451,-32.391152,111.313654,2312.427785,-24.603204,84.550017,0.261767,-0.899575,3.091429
2026-02-13,10172400,0.005435,64.714704,45.264447,-0.628034,1.619858,103477721760000,55284.728882,6.583039e+08,4.604481e+08,...,4187.992886,2929.275260,-40.643031,104.828646,2048.870135,-28.427609,73.321987,0.394427,-1.017326,2.623941
2026-02-16,6330000,-0.005405,62.073209,43.657935,-0.664141,1.633292,40068900000000,-34216.183144,3.929234e+08,2.763547e+08,...,3853.083303,2709.988120,-41.225361,101.383666,1906.015270,-28.995023,71.306148,0.441083,-1.084736,2.667642

In [5]:
X_norm= apply_zscore_normalization(data_fe, model['mu'], model['sigma'], model['features_to_scale'])
X_norm

,volume,pct_change_1d,rsi,adx,corr,volatility,volume^2,volume*pct_change_1d,volume*rsi,volume*adx,...,rsi^2,rsi*adx,rsi*corr,rsi*volatility,adx^2,adx*corr,adx*volatility,corr^2,corr*volatility,volatility^2
Date,,,,,,,,,,,,,,,,,,,,,
2026-02-03,1.633906,-1.213104,1.069129,4.093868,0.579944,1.939089,1.378152,-1.637124,1.949728,5.005858,...,1.016148,4.532219,0.776753,0.689576,6.358162,2.100685,2.194320,0.336335,0.414198,-0.107664
2026-02-04,0.311099,0.592810,1.268403,3.659461,0.258942,1.953325,0.029722,0.426278,0.721684,2.266818,...,1.259894,4.359536,-0.031843,0.827776,5.390288,0.433808,1.983274,0.067051,-0.225956,-0.093298
2026-02-05,1.170306,-1.226306,0.579082,3.124709,-0.180845,1.989508,0.829582,-1.432757,1.202786,3.345817,...,0.458574,3.033038,-1.157787,0.469060,4.288460,-1.522582,1.748455,0.032705,-1.121466,-0.056311
2026-02-06,0.373737,0.599713,0.811055,2.599600,-0.512682,1.989921,0.078515,0.447094,0.592227,1.755644,...,0.715098,2.815483,-1.998873,0.608852,3.302735,-2.721943,1.456534,0.262842,-1.804696,-0.055884
2026-02-09,-0.181160,1.203686,1.225129,2.234913,-0.847745,2.112623,-0.301621,0.674391,0.200652,0.788230,...,1.206126,2.879124,-3.014355,1.042289,2.674260,-3.774986,1.418280,0.718672,-2.602109,0.074629
2026-02-10,0.583516,-0.316821,1.043715,1.906694,-0.878577,1.656947,0.252827,-0.329998,0.897603,1.614747,...,0.985770,2.387812,-3.011450,0.265053,2.147958,-3.671025,0.653470,0.771897,-2.255311,-0.370716
2026-02-11,-0.078395,1.183544,1.435536,1.680116,-0.680924,1.794609,-0.240085,0.711178,0.375508,0.673425,...,1.471910,2.502711,-2.642833,0.677051,1.806373,-2.901911,0.712015,0.463657,-2.013468,-0.247525
2026-02-12,0.372112,-0.605944,1.062425,1.420093,-0.511632,1.758246,0.077230,-0.542111,0.697272,1.062172,...,1.008119,1.933225,-2.065539,0.422058,1.436246,-2.270909,0.540772,0.261767,-1.679906,-0.281021
2026-02-13,0.179286,0.279075,1.169672,1.186072,-0.628034,1.619858,-0.068066,0.161042,0.547806,0.720400,...,1.137900,1.787203,-2.404679,0.272752,1.123124,-2.505728,0.280177,0.394427,-1.801728,-0.402225
2026-02-16,-0.530268,-0.313592,0.968070,1.052908,-0.664141,1.633292,-0.480573,-0.196748,-0.217735,-0.076710,...,0.896295,1.509085,-2.428612,0.193437,0.953403,-2.540567,0.233391,0.441083,-1.871468,-0.390895

In [6]:
future_1d_returns

Date
2026-02-03    0.011173
2026-02-04   -0.022099
2026-02-05    0.011299
2026-02-06    0.022346
2026-02-09   -0.005464
2026-02-10    0.021978
2026-02-11   -0.010753
2026-02-12    0.005435
2026-02-13   -0.005405
2026-02-16    0.016304
Name: future_1d_returns, dtype: float64

In [7]:
import numpy as np
ALL_TRAINING_FEATURES = [
    'volume', 'pct_change_1d', 'rsi', 'adx', 'corr', 'volatility',
    'volume^2', 'pct_change_1d^2', 'rsi^2', 'adx^2', 'corr^2', 'volatility^2',
    'volume*pct_change_1d', 'volume*rsi', 'volume*adx', 'volume*corr', 
    'volume*volatility', 'pct_change_1d*rsi', 'pct_change_1d*adx', 
    'pct_change_1d*corr', 'pct_change_1d*volatility', 'rsi*adx', 'rsi*corr', 
    'rsi*volatility', 'adx*corr', 'adx*volatility', 'corr*volatility'
]

In [8]:
print(X_norm[ALL_TRAINING_FEATURES].columns)
print(model['weights'])

Index(['volume', 'pct_change_1d', 'rsi', 'adx', 'corr', 'volatility',
       'volume^2', 'pct_change_1d^2', 'rsi^2', 'adx^2', 'corr^2',
       'volatility^2', 'volume*pct_change_1d', 'volume*rsi', 'volume*adx',
       'volume*corr', 'volume*volatility', 'pct_change_1d*rsi',
       'pct_change_1d*adx', 'pct_change_1d*corr', 'pct_change_1d*volatility',
       'rsi*adx', 'rsi*corr', 'rsi*volatility', 'adx*corr', 'adx*volatility',
       'corr*volatility'],
      dtype='str')
[ 0.10420549 -0.52079175 -0.41705808  0.12061994  0.24286792  0.44700312
  0.03788581 -0.06492184  0.19082469  0.53794669  0.32588546  0.07008246
  0.15135067  0.22252467 -0.06476562  0.37409437  0.06320299  0.01156817
  0.0409008   0.05777237  0.11835459 -0.30667039 -0.11492176  0.12208219
 -0.1908274  -0.78291617 -0.12055786]

In [11]:
def sigmoid(z):
    z = np.clip(z, -500, 500)
    f_wb = 1 / (1 + np.exp(-z))

    return f_wb

In [12]:
y_hat = np.where(sigmoid(np.dot(X_norm[ALL_TRAINING_FEATURES].values, model['weights']) + model['bias']) >= 0.5, 1, 0)
y_hat

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [14]:
actual = np.where(future_1d_returns > 0, 1, 0)

In [17]:
np.mean(y_hat == actual)

np.float64(0.6)