In [1]:
import pandas as pd
import numpy as np
import pickle

import sys
sys.path.insert(0, '..')

from utilities_notebook import zscore_normalize_features, apply_zscore_normalization, get_engineered_data
import yfinance as yf

from datetime import datetime
from zoneinfo import ZoneInfo

# Load your model to check the 'expected_features'
with open('../model.pkl', 'rb') as f:
    model = pickle.load(f)

In [2]:
model

{'weights': array([ 0.10420549, -0.52079175, -0.41705808,  0.12061994,  0.24286792,
         0.44700312,  0.03788581, -0.06492184,  0.19082469,  0.53794669,
         0.32588546,  0.07008246,  0.15135067,  0.22252467, -0.06476562,
         0.37409437,  0.06320299,  0.01156817,  0.0409008 ,  0.05777237,
         0.11835459, -0.30667039, -0.11492176,  0.12208219, -0.1908274 ,
        -0.78291617, -0.12055786]),
 'bias': np.float64(-1.4475714946980056),
 'mu': volume                  9.201526e+06
 pct_change_1d           3.303557e-04
 rsi                     4.938905e+01
 adx                     3.095551e+01
 volume^2                1.139406e+14
 pct_change_1d^2         3.340574e-04
 rsi^2                   2.610649e+03
 adx^2                   1.103528e+03
 volatility^2            4.175331e+00
 volume*pct_change_1d    1.500027e+04
 volume*rsi              4.684029e+08
 volume*adx              2.940709e+08
 volume*corr             3.600314e+06
 volume*volatility       1.814237e+07
 pct_change_1d*rsi       1.030347e-01
 pct_change_1d*adx       1.422425e-02
 pct_change_1d*corr      5.723908e-05
 rsi*adx                 1.520124e+03
 rsi*corr                1.786711e+01
 rsi*volatility          9.298190e+01
 adx*corr                1.238225e+01
 adx*volatility          6.125020e+01
 corr*volatility         7.242037e-01
 dtype: float64,
 'sigma': volume                  5.415230e+06
 pct_change_1d           1.829053e-02
 rsi                     1.310252e+01
 adx                     1.206415e+01
 volume^2                1.537159e+14
 pct_change_1d^2         6.073698e-04
 rsi^2                   1.386189e+03
 adx^2                   8.417080e+02
 volatility^2            3.857020e+00
 volume*pct_change_1d    2.501494e+05
 volume*rsi              3.466572e+08
 volume*adx              2.309509e+08
 volume*corr             5.423887e+06
 volume*volatility       1.520310e+07
 pct_change_1d*rsi       9.402993e-01
 pct_change_1d*adx       6.158278e-01
 pct_change_1d*corr      1.072959e-02
 rsi*adx                 7.884670e+02
 rsi*corr                2.433179e+01
 rsi*volatility          4.343421e+01
 adx*corr                1.628663e+01
 adx*volatility          4.308625e+01
 corr*volatility         9.665887e-01
 dtype: float64,
 'features_to_scale': ['volume',
  'pct_change_1d',
  'rsi',
  'adx',
  'volume^2',
  'pct_change_1d^2',
  'rsi^2',
  'adx^2',
  'volatility^2',
  'volume*pct_change_1d',
  'volume*rsi',
  'volume*adx',
  'volume*corr',
  'volume*volatility',
  'pct_change_1d*rsi',
  'pct_change_1d*adx',
  'pct_change_1d*corr',
  'rsi*adx',
  'rsi*corr',
  'rsi*volatility',
  'adx*corr',
  'adx*volatility',
  'corr*volatility']}

In [3]:
import numpy as np
ALL_TRAINING_FEATURES = [
    'volume', 'pct_change_1d', 'rsi', 'adx', 'corr', 'volatility',
    'volume^2', 'pct_change_1d^2', 'rsi^2', 'adx^2', 'corr^2', 'volatility^2',
    'volume*pct_change_1d', 'volume*rsi', 'volume*adx', 'volume*corr', 
    'volume*volatility', 'pct_change_1d*rsi', 'pct_change_1d*adx', 
    'pct_change_1d*corr', 'pct_change_1d*volatility', 'rsi*adx', 'rsi*corr', 
    'rsi*volatility', 'adx*corr', 'adx*volatility', 'corr*volatility'
]

In [4]:
def sigmoid(z):
    z = np.clip(z, -500, 500)
    f_wb = 1 / (1 + np.exp(-z))

    return f_wb

In [5]:


data = yf.download('5296.KL', period='30d', multi_level_index=False)
data

[*********************100%***********************]  1 of 1 completed

            Close  High   Low  Open    Volume
Date
2026-01-07   1.56  1.56  1.50  1.52  12231500
2026-01-08   1.54  1.55  1.53  1.55   9367900
2026-01-09   1.58  1.59  1.53  1.55  17083700
2026-01-12   1.63  1.63  1.56  1.58  21047500
2026-01-13   1.67  1.69  1.62  1.63  20931300
2026-01-14   1.73  1.73  1.65  1.67  22948000
2026-01-15   1.72  1.74  1.68  1.73  20878000
2026-01-16   1.73  1.73  1.70  1.72  21296100
2026-01-19   1.73  1.73  1.73  1.73         0
2026-01-20   1.74  1.77  1.69  1.71  20655500
2026-01-21   1.78  1.79  1.74  1.74  19521400
2026-01-22   1.80  1.81  1.75  1.78  27050900
2026-01-23   1.81  1.87  1.79  1.80  34530300
2026-01-26   1.88  1.90  1.81  1.81  31199100
2026-01-27   1.90  1.91  1.88  1.88  18945500
2026-01-28   1.87  1.90  1.86  1.90  12225800
2026-01-29   1.83  1.87  1.81  1.87  12947400
2026-01-30   1.83  1.86  1.82  1.83  12121200
2026-02-03   1.79  1.87  1.79  1.84  18049500
2026-02-04   1.81  1.83  1.79  1.79  10886200
2026-02-05   1.77  1.83  1.76  1.81  15539000
2026-02-06   1.79  1.82  1.75  1.75  11225400
2026-02-09   1.83  1.85  1.80  1.80   8220500
2026-02-10   1.82  1.85  1.81  1.84  12361400
2026-02-11   1.86  1.87  1.82  1.83   8777000
2026-02-12   1.84  1.86  1.81  1.85  11216600
2026-02-13   1.85  1.86  1.82  1.84  10172400
2026-02-16   1.84  1.88  1.83  1.85   6330000
2026-02-19   1.87  1.89  1.84  1.84   6376600
2026-02-20   1.87  1.88  1.84  1.87   5870800

In [6]:
def is_market_ticking(ticker_symbol):
    ticker = yf.Ticker(ticker_symbol)
    
    state = ticker.info.get('marketState')

    if state == 'REGULAR' or state == 'PRE':
        return True
    else:
        return False

In [7]:
is_market_ticking('5296.KL')

False

In [8]:
tick = yf.Ticker('5296.KL')
dat = tick.history(period='2d', interval='4h')
dat2 = yf.download(tickers='5296.KL', period='5d')
dat2

[*********************100%***********************]  1 of 1 completed

Price        Close    High     Low    Open    Volume
Ticker     5296.KL 5296.KL 5296.KL 5296.KL   5296.KL
Date
2026-02-12    1.84    1.86    1.81    1.85  11216600
2026-02-13    1.85    1.86    1.82    1.84  10172400
2026-02-16    1.84    1.88    1.83    1.85   6330000
2026-02-19    1.87    1.89    1.84    1.84   6376600
2026-02-20    1.87    1.88    1.84    1.87   5870800